- name: "lauch the CI Pipeline"
  hosts: prod
  become: true
  vars_files:
    - secrets.yml
  roles:
    - docker_role
  tasks:
    - name: "create project dir"
      file:
        path: /home/{{ ansible_user }}/tower_ci/app_files
        state: directory
        recurse: yes

    - name: "copy project files on remote host"
      copy:
        src: "{{ playbook_dir }}/app_files/"
        dest: /home/{{ ansible_user }}/tower_ci/app_files/

    - name: "generate pipeline files template"
      template:
        src: "{{ item }}"
        dest: /home/{{ ansible_user }}/tower_ci/{{ item }}
      loop:
        - build.sh.j2
        - save_artifact.sh.j2
        - test.sh.j2
    
    - name: "build the dockerfile"
      command: "sh /home/{{ ansible_user }}/tower_ci/build.sh.j2"
      args:
        chdir: "home/{{ ansible_user }}/tower_ci/"
    
    - name: "test image "
      command: "sh /home/{{ ansible_user }}/tower_ci/test.sh.j2"
    
    - name: "save artifact "
      command: "sh /home/{{ ansible_user }}/tower_ci/save_artifact.sh.j2"

    