all:
  vars:
    IMAGE_NAME: "alpinehelloworld"
    IMAGE_TAG: "latest"
    CONTAINER_NAME: "alpinehelloworld-test"
    USERNAME: "sadofrazer"
    VAULT_DOCKERHUB_PASSWORD: "{{ DOCKERHUB_PASSWORD }}"
prod:
  hosts:
    worker01:
      ansible_user: "ubuntu"
      ansible_host: ""

tower:
  hosts:
    master:
      ansible_connection: local
      ansible_host: localhost
    